export const DB_NAME = 'cine_mongolia_fullstack_db';
export const DB_VERSION = 6;
const now = () => new Date().toISOString();

const sampleMovieData = [
  {
    "id": 201,
    "title": "Sintel",
    "originalTitle": "Sintel (2010)",
    "genre": "Open Movie",
    "genreKey": "open-movie",
    "rating": 8.6,
    "year": 2010,
    "duration": "14м 48с",
    "age": "13+",
    "is3D": true,
    "mongolian": false,
    "isReal": true,
    "modernLegal": true,
    "quality": "HD",
    "license": "Creative Commons Attribution 3.0",
    "source": "Blender Foundation",
    "embedSrc": "https://www.youtube.com/embed/eRsGyueVLvQ",
    "desc": "Синтел нэртэй охин найз болсон бяцхан луугаа хайхаар аюултай аялалд гарна. Найз нөхөрлөл, алдагдал, цаг хугацааны тухай 3D fantasy богино кино.",
    "views": 928217,
    "img": "https://i.ytimg.com/vi/aqz-KE-bpKQ/hqdefault.jpg",
    "imgWide": "https://i.ytimg.com/vi/aqz-KE-bpKQ/hqdefault.jpg",
    "videoSrc": ""
  },
  {
    "id": 202,
    "title": "Big Buck Bunny",
    "originalTitle": "Big Buck Bunny (2008)",
    "genre": "Open Movie",
    "genreKey": "open-movie",
    "rating": 8.2,
    "year": 2008,
    "duration": "10м",
    "age": "Бүх нас",
    "is3D": true,
    "mongolian": false,
    "isReal": true,
    "modernLegal": true,
    "quality": "4K/60fps",
    "license": "Creative Commons Attribution",
    "source": "Blender Foundation",
    "embedSrc": "https://www.youtube.com/embed/aqz-KE-bpKQ",
    "desc": "Том зүрхтэй аварга туулай ойд амьдардаг жижиг амьтдын дээрэлхэлтэй нүүр тулж, хөгжилтэй байдлаар хариу барина. Өнгөлөг 3D comedy animation.",
    "views": 875000,
    "img": "https://i.ytimg.com/vi/aqz-KE-bpKQ/hqdefault.jpg",
    "imgWide": "https://i.ytimg.com/vi/aqz-KE-bpKQ/maxresdefault.jpg",
    "videoSrc": ""
  },
  {
    "id": 203,
    "title": "Elephants Dream",
    "originalTitle": "Elephants Dream (2006)",
    "genre": "Sci-Fi Animation",
    "genreKey": "sci-fi",
    "rating": 7.5,
    "year": 2006,
    "duration": "10м 53с",
    "age": "13+",
    "is3D": true,
    "mongolian": false,
    "isReal": true,
    "modernLegal": true,
    "quality": "HD",
    "license": "Creative Commons Attribution",
    "source": "Blender Foundation",
    "embedSrc": "https://archive.org/embed/ElephantsDream",
    "desc": "Проог, Эмо хоёр аварга машин мэт сюрреал ертөнцөөр аялна. Blender open movie төслийн эхэн үеийн experimental sci-fi animation.",
    "views": 420000,
    "img": "https://archive.org/services/img/ElephantsDream",
    "imgWide": "https://archive.org/services/img/ElephantsDream",
    "videoSrc": ""
  },
  {
    "id": 204,
    "title": "Tears of Steel",
    "originalTitle": "Tears of Steel (2012)",
    "genre": "Sci-Fi / VFX",
    "genreKey": "sci-fi",
    "rating": 8.1,
    "year": 2012,
    "duration": "12м 14с",
    "age": "13+",
    "is3D": false,
    "mongolian": false,
    "isReal": true,
    "modernLegal": true,
    "quality": "4K",
    "license": "Creative Commons Attribution 3.0",
    "source": "Blender Foundation",
    "embedSrc": "https://www.youtube.com/embed/R6MlUcmOul8",
    "desc": "Амстердамын ирээдүйн орчинд хоёр хүний уулзалт хүн төрөлхтнийг хиймэл оюунт дайснаас аврах оролдлоготой холбогдоно. Live action ба CGI VFX хосолсон кино.",
    "views": 1200000,
    "img": "https://i.ytimg.com/vi/R6MlUcmOul8/hqdefault.jpg",
    "imgWide": "https://i.ytimg.com/vi/R6MlUcmOul8/maxresdefault.jpg",
    "videoSrc": ""
  },
  {
    "id": 205,
    "title": "Spring",
    "originalTitle": "Spring (2019)",
    "genre": "Fantasy Animation",
    "genreKey": "fantasy",
    "rating": 8.4,
    "year": 2019,
    "duration": "7м 44с",
    "age": "Бүх нас",
    "is3D": true,
    "mongolian": false,
    "isReal": true,
    "modernLegal": true,
    "quality": "HD",
    "license": "Creative Commons Attribution",
    "source": "Blender Studio",
    "embedSrc": "https://www.youtube.com/embed/WhWc3b3KhnY",
    "desc": "Залуу хоньчин охин, түүний нохой хоёр улирлын өөрчлөлтийг авчрахын тулд эртний байгалийн сүнслэг хүчнүүдтэй учирна. Маш үзэсгэлэнтэй fantasy open movie.",
    "views": 1600000,
    "img": "https://i.ytimg.com/vi/WhWc3b3KhnY/hqdefault.jpg",
    "imgWide": "https://i.ytimg.com/vi/WhWc3b3KhnY/maxresdefault.jpg",
    "videoSrc": ""
  },
  {
    "id": 206,
    "title": "Sprite Fright",
    "originalTitle": "Sprite Fright (2021)",
    "genre": "Horror Comedy",
    "genreKey": "horror",
    "rating": 8.0,
    "year": 2021,
    "duration": "10м 30с",
    "age": "13+",
    "is3D": true,
    "mongolian": false,
    "isReal": true,
    "modernLegal": true,
    "quality": "HD",
    "license": "Creative Commons Attribution",
    "source": "Blender Studio",
    "embedSrc": "https://www.youtube.com/embed/_cMxraX_5RE",
    "desc": "Ойд аялж яваа залуус байгальд хайнга хандсанаас болж жижиг сүнслэг амьтадтай таарна. 1980-аад оны horror-comedy өнгө аястай stylized 3D animation.",
    "views": 2100000,
    "img": "https://i.ytimg.com/vi/_cMxraX_5RE/hqdefault.jpg",
    "imgWide": "https://i.ytimg.com/vi/_cMxraX_5RE/maxresdefault.jpg",
    "videoSrc": ""
  },
  {
    "id": 207,
    "title": "CHARGE",
    "originalTitle": "CHARGE (2022)",
    "genre": "Cinematic Animation",
    "genreKey": "action",
    "rating": 8.5,
    "year": 2022,
    "duration": "4м 23с",
    "age": "13+",
    "is3D": true,
    "mongolian": false,
    "isReal": true,
    "modernLegal": true,
    "quality": "HD",
    "license": "Creative Commons Attribution",
    "source": "Blender Studio",
    "embedSrc": "https://www.youtube.com/embed/UXqq0ZvbOnk",
    "desc": "Исланд маягийн байгалийн орчинд өрнөх богино cinematic open movie. Photoreal lighting, PBR texture, action mood-оороо орчин үеийн дүрслэлтэй.",
    "views": 900000,
    "img": "https://i.ytimg.com/vi/UXqq0ZvbOnk/hqdefault.jpg",
    "imgWide": "https://i.ytimg.com/vi/UXqq0ZvbOnk/maxresdefault.jpg",
    "videoSrc": ""
  },
  {
    "id": 208,
    "title": "WING IT!",
    "originalTitle": "WING IT! (2023)",
    "genre": "Comedy Animation",
    "genreKey": "comedy",
    "rating": 8.2,
    "year": 2023,
    "duration": "3м 58с",
    "age": "Бүх нас",
    "is3D": true,
    "mongolian": false,
    "isReal": true,
    "modernLegal": true,
    "quality": "HD",
    "license": "Blender Open Movie",
    "source": "Blender Studio",
    "embedSrc": "https://www.youtube.com/embed/u9lj-c29dxI",
    "desc": "Дүрэмч, нямбай инженер муурын зохион бүтээсэн сансрын төхөөрөмж рүү адал явдалд дуртай нохой гэнэт орж ирснээр хөгжилтэй үйл явдал эхэлнэ.",
    "views": 800000,
    "img": "https://i.ytimg.com/vi/u9lj-c29dxI/hqdefault.jpg",
    "imgWide": "https://i.ytimg.com/vi/u9lj-c29dxI/maxresdefault.jpg",
    "videoSrc": ""
  },
  {
    "id": 209,
    "title": "Coffee Run",
    "originalTitle": "Coffee Run (2020)",
    "genre": "Romance Animation",
    "genreKey": "romance",
    "rating": 7.9,
    "year": 2020,
    "duration": "3м 05с",
    "age": "13+",
    "is3D": true,
    "mongolian": false,
    "isReal": true,
    "modernLegal": true,
    "quality": "HD",
    "license": "Blender Open Movie",
    "source": "Blender Studio",
    "embedSrc": "https://www.youtube.com/embed/PVGeM40dABA",
    "desc": "Кофе авах энгийн алхалт залуу бүсгүйн дурсамж, хайр дурлалын мэдрэмжтэй холбогдон өнгөлөг animation хэлбэрээр өрнөнө.",
    "views": 900000,
    "img": "https://i.ytimg.com/vi/PVGeM40dABA/hqdefault.jpg",
    "imgWide": "https://i.ytimg.com/vi/PVGeM40dABA/maxresdefault.jpg",
    "videoSrc": ""
  },
  {
    "id": 210,
    "title": "HERO",
    "originalTitle": "HERO — Grease Pencil Showcase (2018)",
    "genre": "2D/3D Animation",
    "genreKey": "animation",
    "rating": 7.8,
    "year": 2018,
    "duration": "4м",
    "age": "Бүх нас",
    "is3D": false,
    "mongolian": false,
    "isReal": true,
    "modernLegal": true,
    "quality": "HD",
    "license": "Creative Commons Attribution 4.0",
    "source": "Blender Foundation",
    "embedSrc": "https://www.youtube.com/embed/pKmSdY56VtY",
    "desc": "Blender-ийн Grease Pencil технологийг харуулах зорилготой comic-style богино кино. 2D зураас ба 3D орчныг нэгтгэсэн өвөрмөц дүрслэлтэй.",
    "views": 700000,
    "img": "https://i.ytimg.com/vi/pKmSdY56VtY/hqdefault.jpg",
    "imgWide": "https://i.ytimg.com/vi/pKmSdY56VtY/maxresdefault.jpg",
    "videoSrc": ""
  },
  {
    "id": 211,
    "title": "Agent 327: Operation Barbershop",
    "originalTitle": "Agent 327: Operation Barbershop (2017)",
    "genre": "Action Comedy",
    "genreKey": "action",
    "rating": 8.1,
    "year": 2017,
    "duration": "3м 52с",
    "age": "13+",
    "is3D": true,
    "mongolian": false,
    "isReal": true,
    "modernLegal": true,
    "quality": "HD",
    "license": "Blender Open Movie",
    "source": "Blender Animation Studio",
    "embedSrc": "https://www.youtube.com/embed/Y-rmzh0PI3c",
    "desc": "Нууц агент 327 энгийн үсчний газар мэт харагдах газарт орж ирээд гэнэтийн мөргөлдөөнтэй тулгарна. Богино, хурдтай, action-comedy teaser.",
    "views": 850000,
    "img": "https://i.ytimg.com/vi/Y-rmzh0PI3c/hqdefault.jpg",
    "imgWide": "https://i.ytimg.com/vi/Y-rmzh0PI3c/maxresdefault.jpg",
    "videoSrc": ""
  },
  {
    "id": 212,
    "title": "The Daily Dweebs",
    "originalTitle": "The Daily Dweebs (2017)",
    "genre": "Comedy Animation",
    "genreKey": "comedy",
    "rating": 7.6,
    "year": 2017,
    "duration": "3м 15с",
    "age": "Бүх нас",
    "is3D": true,
    "mongolian": false,
    "isReal": true,
    "modernLegal": true,
    "quality": "HD",
    "license": "Blender Open Movie",
    "source": "Blender Animation Studio",
    "embedSrc": "https://www.youtube.com/embed/RJnKaAtBPhA",
    "desc": "1950-аад оны suburbia өнгө аястай pilot episode. Dixey нэртэй тэжээвэр амьтны өдөр тутмын сахилгагүй, хөгжилтэй явдлыг харуулна.",
    "views": 620000,
    "img": "https://i.ytimg.com/vi/RJnKaAtBPhA/hqdefault.jpg",
    "imgWide": "https://i.ytimg.com/vi/RJnKaAtBPhA/maxresdefault.jpg",
    "videoSrc": ""
  },
  {
    "id": 213,
    "title": "Caminandes: Llamigos",
    "originalTitle": "Caminandes 3: Llamigos (2016)",
    "genre": "Family Animation",
    "genreKey": "animation",
    "rating": 7.7,
    "year": 2016,
    "duration": "2м 30с",
    "age": "Бүх нас",
    "is3D": true,
    "mongolian": false,
    "isReal": true,
    "modernLegal": true,
    "quality": "HD",
    "license": "Creative Commons Attribution",
    "source": "Blender Foundation",
    "embedSrc": "https://www.youtube.com/embed/SkVqJ1SGeL0",
    "desc": "Патагонийн өвлийн орчинд Коро нэртэй ламанд хоол олох амаргүй болно. Caminandes цувралын хөгжилтэй, богино family animation.",
    "views": 520000,
    "img": "https://i.ytimg.com/vi/SkVqJ1SGeL0/hqdefault.jpg",
    "imgWide": "https://i.ytimg.com/vi/SkVqJ1SGeL0/maxresdefault.jpg",
    "videoSrc": ""
  },
  {
    "id": 214,
    "title": "Caminandes: Gran Dillama",
    "originalTitle": "Caminandes 2: Gran Dillama (2013)",
    "genre": "Family Animation",
    "genreKey": "animation",
    "rating": 7.4,
    "year": 2013,
    "duration": "2м 30с",
    "age": "Бүх нас",
    "is3D": true,
    "mongolian": false,
    "isReal": true,
    "modernLegal": true,
    "quality": "HD",
    "license": "Creative Commons Attribution",
    "source": "Blender Foundation",
    "embedSrc": "https://archive.org/embed/Caminandes2GranDillama",
    "desc": "Коро лама зорьсон газраа хүрэхийн тулд саадтай замыг даван гарах гэж хөгжилтэй байдлаар оролдоно. Богино, цэвэр family comedy animation.",
    "views": 380000,
    "img": "https://archive.org/services/img/Caminandes2GranDillama",
    "imgWide": "https://archive.org/services/img/Caminandes2GranDillama",
    "videoSrc": ""
  },
  {
    "id": 101,
    "title": "Night of the Living Dead",
    "originalTitle": "Night of the Living Dead (1968)",
    "genre": "Classic / Public Domain",
    "genreKey": "classic",
    "rating": 8.1,
    "year": 1968,
    "duration": "1ц 36м",
    "age": "16+",
    "is3D": false,
    "mongolian": false,
    "isReal": true,
    "modernLegal": false,
    "quality": "SD/HD",
    "license": "Public Domain Mark",
    "source": "Internet Archive",
    "embedSrc": "https://archive.org/embed/night-of-the-living-dead-1968-english",
    "desc": "Public domain ангиллын сонгодог аймшгийн кино. Алслагдсан байшинд хэсэг хүмүүс гадаад аюулаас хоргодох явцдаа айдас, үл итгэлцэлтэй нүүр тулна.",
    "views": 120000,
    "img": "https://archive.org/services/img/night-of-the-living-dead-1968-english",
    "imgWide": "https://archive.org/services/img/night-of-the-living-dead-1968-english",
    "videoSrc": ""
  },
  {
    "id": 102,
    "title": "The General",
    "originalTitle": "The General (1926)",
    "genre": "Classic / Public Domain",
    "genreKey": "classic",
    "rating": 8.2,
    "year": 1926,
    "duration": "1ц 18м",
    "age": "Бүх нас",
    "is3D": false,
    "mongolian": false,
    "isReal": true,
    "modernLegal": false,
    "quality": "SD/HD",
    "license": "Public Domain",
    "source": "Internet Archive",
    "embedSrc": "https://archive.org/embed/The_General_Buster_Keaton",
    "desc": "Buster Keaton-ийн чимээгүй инээдмийн сонгодог бүтээл. Галт тэрэг, хайр, хурдтай chase scene-үүдээрээ алдартай.",
    "views": 110000,
    "img": "https://archive.org/services/img/The_General_Buster_Keaton",
    "imgWide": "https://archive.org/services/img/The_General_Buster_Keaton",
    "videoSrc": ""
  },
  {
    "id": 103,
    "title": "Nosferatu",
    "originalTitle": "Nosferatu (1922)",
    "genre": "Classic / Public Domain",
    "genreKey": "classic",
    "rating": 7.9,
    "year": 1922,
    "duration": "1ц 34м",
    "age": "13+",
    "is3D": false,
    "mongolian": false,
    "isReal": true,
    "modernLegal": false,
    "quality": "SD/HD",
    "license": "Public Domain Mark",
    "source": "Internet Archive",
    "embedSrc": "https://archive.org/embed/nosferatu-1922_202504",
    "desc": "Германы экспрессионист кино урлагийн сонгодог бүтээл. Count Orlok-ийн сүүдэрлэг дүрслэл, gothic уур амьсгал нь аймшгийн киноны түүхэнд нөлөө үзүүлсэн.",
    "views": 95000,
    "img": "https://archive.org/services/img/nosferatu-1922_202504",
    "imgWide": "https://archive.org/services/img/nosferatu-1922_202504",
    "videoSrc": ""
  },
  {
    "id": 104,
    "title": "A Trip to the Moon",
    "originalTitle": "Le voyage dans la lune (1902)",
    "genre": "Classic / Public Domain",
    "genreKey": "classic",
    "rating": 8.1,
    "year": 1902,
    "duration": "13м",
    "age": "Бүх нас",
    "is3D": false,
    "mongolian": false,
    "isReal": true,
    "modernLegal": false,
    "quality": "SD/HD",
    "license": "Public Domain / Archive copy",
    "source": "Internet Archive",
    "embedSrc": "https://archive.org/embed/Levoyagedanslalune",
    "desc": "Georges Méliès-ийн эртний sci-fi богино кино. Сар руу аялах төсөөлөл, театрчилсан дүрслэлээрээ кино урлагийн түүхэнд алдартай.",
    "views": 90000,
    "img": "https://archive.org/services/img/Levoyagedanslalune",
    "imgWide": "https://archive.org/services/img/Levoyagedanslalune",
    "videoSrc": ""
  }
];

export const sampleMovies = sampleMovieData.map(movie => ({...movie, createdAt: now(), seeded: true}));

export class LocalDatabase {
  constructor(){ this.db=null; }
  open(){
    if(this.db) return Promise.resolve(this.db);
    return new Promise((resolve,reject)=>{
      const req=indexedDB.open(DB_NAME,DB_VERSION);
      req.onupgradeneeded=()=>{
        const db=req.result;
        for(const name of ['movies','users','sessions','profiles','watchlist','watchHistory','reviews','analytics','subscriptions','notifications','chatMessages','settings']){
          if(!db.objectStoreNames.contains(name)) db.createObjectStore(name,{keyPath:name==='sessions'?'token':'id'});
        }
      };
      req.onsuccess=async()=>{this.db=req.result; await this.seed(); resolve(this.db);};
      req.onerror=()=>reject(req.error);
    });
  }
  tx(name,mode='readonly'){return this.db.transaction(name,mode).objectStore(name);}
  get(name,key){return new Promise((res,rej)=>{const r=this.tx(name).get(key); r.onsuccess=()=>res(r.result||null); r.onerror=()=>rej(r.error);});}
  getAll(name){return new Promise((res,rej)=>{const r=this.tx(name).getAll(); r.onsuccess=()=>res(r.result||[]); r.onerror=()=>rej(r.error);});}
  put(name,value){return new Promise((res,rej)=>{const r=this.tx(name,'readwrite').put(value); r.onsuccess=()=>res(value); r.onerror=()=>rej(r.error);});}
  delete(name,key){return new Promise((res,rej)=>{const r=this.tx(name,'readwrite').delete(key); r.onsuccess=()=>res(true); r.onerror=()=>rej(r.error);});}
  clear(name){return new Promise((res,rej)=>{const r=this.tx(name,'readwrite').clear(); r.onsuccess=()=>res(true); r.onerror=()=>rej(r.error);});}
  async find(name,predicate){return (await this.getAll(name)).filter(predicate);}
  id(prefix){return `${prefix}_${crypto.randomUUID?crypto.randomUUID():Date.now()+'_'+Math.random().toString(16).slice(2)}`;}
  async seed(){
    const sampleIds = new Set(sampleMovies.map(movie => Number(movie.id)));
    const existingMovies = await this.getAll('movies');
    for (const movie of existingMovies) {
      const movieId = Number(movie.id);
      const isOldSeed = movie.seeded !== false;
      if (!sampleIds.has(movieId) && isOldSeed) await this.delete('movies', movie.id);
    }
    for (const movie of sampleMovies) await this.put('movies', {...movie, seeded:true, updatedAt:now()});
    if(!(await this.getAll('users')).length){
      const admin={id:'user_admin',name:'Admin',email:'admin@cinemongolia.mn',passwordHash:'admin123',role:'admin',createdAt:now()};
      const user={id:'user_demo',name:'Demo User',email:'user@cinemongolia.mn',passwordHash:'user123',role:'user',createdAt:now()};
      await this.put('users',admin); await this.put('users',user);
      await this.put('profiles',{id:'profile_admin_main',userId:admin.id,name:'Admin',avatar:'A',maturity:'all',active:true,createdAt:now()});
      await this.put('profiles',{id:'profile_demo_main',userId:user.id,name:'Nandin',avatar:'N',maturity:'all',active:true,createdAt:now()});
      await this.put('profiles',{id:'profile_demo_kids',userId:user.id,name:'Kids',avatar:'K',maturity:'13',active:false,createdAt:now()});
      await this.put('subscriptions',{id:'sub_demo',userId:user.id,plan:'standard',status:'active',startedAt:now()});
    }
  }
  async reset(){for(const s of Array.from(this.db.objectStoreNames)) await this.clear(s); await this.seed();}
}
export function clone(value){return JSON.parse(JSON.stringify(value));}
export function makeTimestamp(){return now();}
